# Manifest file for user Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-dev
  template:
    metadata:
      labels:
        app: user-dev
    spec:
      containers:
      - name: user-dev
        image: DIT

---
apiVersion: v1
kind: Service
metadata:
  name: user-dev-svc
spec:
  selector:
    app: user-dev
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8232