# Manifest file for Eureka Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-dev
  template:
    metadata:
      labels:
        app: eureka-dev
    spec:
      containers:
      - name: eureka-dev
        image: DIT

---
apiVersion: v1
kind: Service
metadata:
  name: eureka-dev-svc
spec:
  selector:
    app: eureka-dev
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8761